---
title: "graficos"
author: "Julia Kaori Kuriyama Ramos"
date: "`r Sys.Date()`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
```


## GGPLOT
#Exemplos de gráficos pelo pacote ggplot2 gerados pela disciplina "Ferramentas computacionais 2025"

```{r, echo=FALSE}
library(rcartocolor)
library(tidyverse)
cores <- carto_pal(12,"Bold")
scales::show_col(cores)

dados <- read.csv("Pokemon_full.csv")

summary(dados)
```
```{r}


dados<-dados %>%
  mutate(
    classe_altura = case_when(
      height < 5 ~ "Baixo", 
      height < 50 ~ "Pequeno",
      height < 100 ~ "Médio",
      TRUE ~ "Alto"
    )
  ) %>%
  mutate(
    classe_altura = factor(classe_altura, levels = c("Baixo","Pequeno", "Médio", "Alto")))

  ggplot(dados, aes(x = classe_altura, y = weight, fill = classe_altura)) +
    geom_violin()+
    geom_boxplot(width = 0.2, fill = "white") +
    labs(x = "Classe altura", y = "Peso")+
    scale_y_continuous(trans = "log10")+
    scale_fill_manual(values = cores[c(1,2,3,7)])+
    theme_bw()+
    theme(
      axis.text = element_text(size = 14),
      axis.title = element_text(size = 16, face = "bold"),
      legend.position = "none"
    )



```

```{r}

dados%>%
  arrange(desc(classe_altura))%>%
ggplot(aes(x = weight, y = height, color = classe_altura)) +
  geom_point(alpha = 0.4, size = 2) +
    labs(x = "Peso", y = "Altura", color = "Classe altura")+
    scale_y_continuous(trans = "log10")+
  scale_color_manual(values = cores[c(1,2,3,7)])+
  guides(color = guide_legend(override.aes = list(size = 4)))+
    theme_bw()+
    theme(
      axis.text = element_text(size = 14),
      axis.title = element_text(size = 16, face = "bold"),
      legend.position = "right",
      legend.text = element_text(size = 14),
      legend.title = element_text(size = 16, face = "bold")
    )

```

### Gráfico facetados e de dois eixos

```{r}
dados %>%
  group_by(classe_altura) %>%
  summarise(
    media_h = mean(height),
    media_w = mean(weight)
  ) %>%
  pivot_longer(cols = c(2,3), values_to = "valor", names_to = "Tipo") %>%
  ggplot(aes(x = Tipo, y = valor, fill = classe_altura))+
  geom_col()+
  facet_wrap(.~classe_altura) +
  theme_bw()+
    theme(
      axis.text = element_text(size = 14),
      axis.title = element_text(size = 16, face = "bold"),
      legend.position = "none"
    )

```

```{r}

df_media<-dados %>%
  group_by(classe_altura) %>%
  summarise(
    media_h = mean(height),
    media_w = mean(weight)
  ) %>%
  pivot_longer(cols = c(2,3), values_to = "valor", names_to = "Tipo") %>%
  mutate(
    Medida = case_when(
      grepl("_h", Tipo) ~"Altura",
      TRUE ~"Peso"
    )
  )

max_alt <- df_media %>%
  filter(Medida == "Altura")%>%
  arrange(desc(valor))%>%
  distinct(Medida, .keep_all = T) %>% pull(valor)

max_pes <- df_media %>%
  filter(Medida == "Peso")%>%
  arrange(desc(valor))%>%
  distinct(Medida, .keep_all = T) %>% pull(valor)
fator <- max_pes/max_alt
df_media%>%
  mutate(
    valor2 = ifelse(Medida == "Altura", valor*fator, valor)
  )%>%
  ggplot( aes(x = classe_altura, y = valor2, fill = Tipo))+
  geom_col(position = position_dodge2())+
  labs(x = "Classe", y = "Valor", fill = "Medida")+
  #facet_wrap(.~classe_altura) +
  scale_y_continuous(
    sec.axis = sec_axis(~./fator, name = "Média da Altura")
  )+
  theme_bw()+
    theme(
      axis.text = element_text(size = 14),
      axis.title = element_text(size = 16, face = "bold"),
      legend.position = "right"
    )


```

## mapa dengue em SP

```{r, echo = TRUE}
library(sf)
```


```{r}
dados <- read.csv2("dengue_sp.csv")

head(dados)
```
#Garantir que no conjunto de dados só tenha municípios válidos

```{r}
#trocar o nome da primeira coluna
dados <- dados %>% rename(municipio = 1)
glimpse(dados)
df <- dados %>%
  filter(grepl("\\d{6}", municipio)) %>%
  mutate(across(starts_with("X"), as.integer)) %>%
  pivot_longer(2:13, names_to = "Ano", values_to = "Casos") %>%
  filter(Ano != "Total") %>%
  mutate(
    Ano = str_remove(Ano, "X")
  ) %>%
  mutate(
    Cod = str_extract(municipio, "\\d{6}")
  )



```
Lendo dados da população

```{r}

pop <- read.csv2("tabela4709.csv", skip = 3)
names(pop) <- c("Cod", "Municipio", "Populacao")

pop <- pop %>%
  mutate(
    Cod = str_remove(Cod, "\\d$")
  )
```

Calculando taxas

```{r}

df <- df %>%
  left_join(pop) %>%
  mutate(
    taxa = Casos/Populacao*10000
  )

```

Lendo o arquivo SHP

```{r}
library(sf)
sp_shp <- read_sf("Mapa/SHP/SHP/cidades_SP.shp")

plot(sp_shp$geometry)
```

Juntar os dados

```{r}

df <- sp_shp %>%
  select(CD_GEOCODM, geometry) %>%
  mutate(
    Cod = str_remove(CD_GEOCODM, "\\d$")
  ) %>%
  right_join(df) 

```

Gráfico

```{r}

ggplot(df) +
  geom_sf(aes(color = taxa)) +
  scale_colour_viridis_c()+
  labs(color = "Taxa de incidência") +
  facet_wrap(.~Ano)+
  theme_minimal()
```

